server:
  port: 8080
  servlet:
    context-path: /api
  #  ssl:
  #    key-store: classpath:mykeystore.jks
  #    key-store-password: password
  #    key-store-type: JKS
  #    key-alias: mydomain
  address: 192.168.0.3
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/news_backend"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "xEC1/JAy43Ctoq/UeEYNDVd1IDI5JO5uji7D9SJ3TmLtFu9e6PPo35we27ElT1Fc"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds